server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  #做为网关 设置路由
  cloud:
    gateway:
      routes:
        - id: payment_routh #路由id
          #          uri: http://localhost:8001 #匹配后提供服务的地址
          uri: lb://cloud-payment-service #动态的负载均衡的路由
          predicates:
            - Path=/payment/get/**  #断言，路径相匹配的进行路由
        - id: payment_routh2
          uri: lb://cloud-payment-service
          #          uri: http://localhost:8001
          predicates:
            - Path=/payment/lb/**
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-register: true
      defaultZone:  http://eureka7001.com:7001/eureka
